"use strict";
// PROBLEMA 2
// Each new term in the Fibonacci sequence is generated by adding 
// the previous two terms. By starting with 1 and 2, the first 10 
// terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values 
// do not exceed four million, find the sum of the even-valued terms.
console.time('problema2');
var num1 = 0, temp = 0, sum = 0;
var num2 = 1;
do {
    if (num2 % 2 == 0) {
        sum = sum + num2;
    }
    temp = num1 + num2;
    num1 = num2;
    num2 = temp;
} while (num2 < 4000000);
console.log(sum);
console.timeEnd('problema2');
